name: 🧪 Validate WSL2 Baseline Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # manual run

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Prepare environment
      - name: 🧩 Update base system
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git bash jq python3 python3-pip

      # 3️⃣ Run your setup script
      - name: ⚙️ Run baseline setup script
        run: |
          chmod +x ./run.sh
          ./run.sh

      # 4️⃣ Verify critical tools
      - name: 🧾 Verify tool availability
        run: |
          echo "-------------------------------------------------------------"
          echo "[i] Verifying essential binaries..."
          for tool in git curl htop nmap jq docker cmatrix; do
            if command -v "$tool" >/dev/null 2>&1; then
              echo "[#] $tool available: $(command -v "$tool")"
            else
              echo "[x] $tool missing!"
              exit 1
            fi
          done

          echo "[i] Checking Python version..."
          python --version || exit 1
          pip3 --version || exit 1
          pip3 show pipenv || { echo "[x] pipenv missing"; exit 1; }

          echo "[i] Checking Docker..."
          docker --version || { echo "[x] docker missing"; exit 1; }

          echo "[i] Listing top-level packages:"
          dpkg -l | grep -E "cmatrix|nmap|htop|git" || true
          echo "[#] Verification complete."

      # 5️⃣ Optional: artifact with install logs
      - name: 📦 Upload install logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: |
            ./run.log
            ~/.bashrc
